# Generated by Django 4.2.17 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(
                choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Card')],
                default='cod',
                max_length=20,
            ),
        ),
    ]
