# Generated by Django 4.2.17 on 2026-04-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=60)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='processed', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cod_pending', 'COD Pending'), ('stock_unavailable', 'Stock Unavailable')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), ('idempotency_key__gt', '')), fields=('user', 'idempotency_key'), name='uniq_order_user_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), ('idempotency_key__gt', '')), fields=('email', 'idempotency_key'), name='uniq_order_guest_idempotency_key'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='store.order'),
        ),
    ]
